name = "breastaware"
main = "worker.js"
compatibility_date = "2025-07-18"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "breastaware-db"
database_id = "a232ed0a-9cc1-4551-8e66-39ce6e142c30"
